name: Make

on:
  push:
    branches: ["main"]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup server environemnt
      run: sudo apt-get install -y libsdl2-mixer-dev
    - name: Compile server
      run: make server
  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile client
      run: make client
